---

- name: query all security groups
  ec2_group_info:
    filters:
      group-name: "{{ secgroupDefault }}" 
  register: regSecGroup
  tags: infra

- name: assign security group id to variable
  set_fact:
    factSecGroup: "{{ regSecGroup.security_groups[0].group_id }}" 
  tags: infra

- name: launch build node
  cloudformation:
    stack_name: "stackBuildOrc8r"
    state: "present"
    template: "roles/cfn/cfnMagmaBuild.json"
    template_parameters:
      paramSecGroup: "{{ factSecGroup }}"
      paramAvlZone: "{{ buildAwsAz }}"
      paramKeyHost: "{{ keyHost }}"
      paramImageId: "{{ buildUbuntuAmi }}"
      paramInstanceType: "{{ buildInstanceType }}"
      paramTagName: "{{ buildTagName }}"
  tags:
    - infra-orc8r

